/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2021-08-24 11:56:07 EDT)
 * on 2021-08-24 at 15:56:28 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.rcsbusinessmessaging.v1.model;

/**
 * Request to check if users are RBM-reachable.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the RCS Business Messaging API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BatchGetUsersRequest extends com.google.api.client.json.GenericJson {

  /**
   * Optional. The agent's unique identifier. Defined by RCS Business Messaging.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String agentId;

  /**
   * List of users' phone numbers in E.164 format.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> users;

  /**
   * Optional. The agent's unique identifier. Defined by RCS Business Messaging.
   * @return value or {@code null} for none
   */
  public java.lang.String getAgentId() {
    return agentId;
  }

  /**
   * Optional. The agent's unique identifier. Defined by RCS Business Messaging.
   * @param agentId agentId or {@code null} for none
   */
  public BatchGetUsersRequest setAgentId(java.lang.String agentId) {
    this.agentId = agentId;
    return this;
  }

  /**
   * List of users' phone numbers in E.164 format.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getUsers() {
    return users;
  }

  /**
   * List of users' phone numbers in E.164 format.
   * @param users users or {@code null} for none
   */
  public BatchGetUsersRequest setUsers(java.util.List<java.lang.String> users) {
    this.users = users;
    return this;
  }

  @Override
  public BatchGetUsersRequest set(String fieldName, Object value) {
    return (BatchGetUsersRequest) super.set(fieldName, value);
  }

  @Override
  public BatchGetUsersRequest clone() {
    return (BatchGetUsersRequest) super.clone();
  }

}
