/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2021-08-24 11:56:07 EDT)
 * on 2021-08-24 at 15:56:28 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.rcsbusinessmessaging.v1.model;

/**
 * A tester for the agent. The agent can interact with verified testers even if the agent has not
 * yet launched.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the RCS Business Messaging API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Tester extends com.google.api.client.json.GenericJson {

  /**
   * The status of the invitation.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String inviteStatus;

  /**
   * This field is set by the RBM platform. Do not include it when creating a tester object. The
   * field resolves "phones/{E.164}/testers", where {E.164} is the tester's phone number in E.164
   * format.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The status of the invitation.
   * @return value or {@code null} for none
   */
  public java.lang.String getInviteStatus() {
    return inviteStatus;
  }

  /**
   * The status of the invitation.
   * @param inviteStatus inviteStatus or {@code null} for none
   */
  public Tester setInviteStatus(java.lang.String inviteStatus) {
    this.inviteStatus = inviteStatus;
    return this;
  }

  /**
   * This field is set by the RBM platform. Do not include it when creating a tester object. The
   * field resolves "phones/{E.164}/testers", where {E.164} is the tester's phone number in E.164
   * format.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * This field is set by the RBM platform. Do not include it when creating a tester object. The
   * field resolves "phones/{E.164}/testers", where {E.164} is the tester's phone number in E.164
   * format.
   * @param name name or {@code null} for none
   */
  public Tester setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  @Override
  public Tester set(String fieldName, Object value) {
    return (Tester) super.set(fieldName, value);
  }

  @Override
  public Tester clone() {
    return (Tester) super.clone();
  }

}
